CREATE TABLE orion_edw.program_id_data (
    layer_pick__c boolean ENCODE raw,
    temperature_type__c character varying(250) ENCODE lzo,
    currencyisocode__c character varying(250) ENCODE lzo,
    annual_committed_revenue__c character varying(250) ENCODE lzo,
    initial_wra_id__c character varying(250) ENCODE lzo,
    sfdc_customer_number__c character varying(250) ENCODE lzo,
    committed_unit_of_measure__c character varying(250) ENCODE lzo,
    commitment_type__c character varying(250) ENCODE lzo,
    site_center__c character varying(2500) ENCODE lzo,
    createdbyid character varying(250) ENCODE lzo,
    program_status__c character varying(250) ENCODE lzo,
    customer_blanket_po__c character varying(2500) ENCODE lzo,
    inbound_time_based_charge__c boolean ENCODE raw,
    partial_billing_integration__c boolean ENCODE raw,
    commitment__c character varying(2500) ENCODE lzo,
    wms_number__c character varying(2500) ENCODE lzo,
    distribution_channel__c character varying(2500) ENCODE lzo,
    retail_billing__c boolean ENCODE raw,
    oracle_business_unit__c character varying(250) ENCODE lzo,
    payment_terms__c character varying(2500) ENCODE lzo,
    agreement_program_id__c character varying(2500) ENCODE lzo,
    annual_committed_amount__c character varying(2500) ENCODE lzo,
    weight_billing_type__c character varying(2500) ENCODE lzo,
    item_family_payload__c character varying(2500) ENCODE lzo,
    shared_commitment_id__c character varying(2500) ENCODE lzo,
    supplier_billing__c boolean ENCODE raw,
    createddate character varying(25000) ENCODE lzo,
    rates_payload__c character varying(25000) ENCODE lzo,
    commitment_calendar_type__c character varying(2500) ENCODE lzo,
    sfdc_billing_site_id__c character varying(250) ENCODE lzo,
    facility_id__c character varying(250) ENCODE lzo,
    au_created_date timestamp without time zone DEFAULT ('now':: character varying):: timestamp without time zone ENCODE az64,
    au_updated_date timestamp without time zone DEFAULT ('now':: character varying):: timestamp without time zone ENCODE az64
) DISTSTYLE AUTO;